- platform: template
  switches:
    balcony_light:
      turn_on: 
        service: script.balcony_light_power_on
      turn_off:
        service: script.balcony_light_power_off
      friendly_name: "Balcony Light"
- platform: broadlink
  mac: 78:0F:77:17:F3:9A
  switches:
    - name: Kitchen lights
      command_on: sgw0ACQNJA0NJCQNDSQkDQ0kJA0kDSQNDSQkDSQNJA0NJA0kJA0kDSQNDSQkDQ0kJA0kDQwAAW8AAAAA
      command_off: sgw0ACQNJA0NJCQNDSQkDQ0kDSQkDSQNDSQkDSQNJA0NJA0kJA0kDSQNJA0kDSQNJA0kDQwAAW8AAAAA
    - name: Living room lights
      command_on: sgw0ACQNJA0NJA0kDSQkDSQNDSQkDSQNDSQkDSQNJA0kDQ0kDSQkDSQNDSQNJCQNJA0kDQwAAW8AAAAA
      command_off: sgw0ACQNDSQkDQ0kJA0NJCQNDSQkDQ0kDSQkDSQNDSQkDSQNDSQNJCQNDSQkDSQNJA0NJAwAAW8AAAAA
    - name: Dining table lights
      command_on: sgw0ACQNDSQNJCQNDSQNJA0kDSQkDQ0kJA0kDSQNDSQNJA0kDSQkDSQNJA0kDSQNJA0NJAwAAW8AAAAA
      command_off: sgw0AA0kJA0kDQ0kJA0NJCQNDSQNJCQNDSQkDSQNJA0NJA0kJA0NJCQNDSQNJCQNJA0kDQwAAW8AAAAA
    - name: Hall lights
      command_on: sgw0AA0kJA0NJCQNJA0NJCQNDSQNJA0kDSQNJA0kJA0kDQ0kJA0NJA0kJA0NJCQNJA0NJAwAAW8AAAAA
      command_off: sgw0AA0kJA0kDSQNJA0NJA0kDSQNJCQNJA0NJCQNJA0kDQ0kJA0NJA0kDSQNJA0kJA0kDQwAAW8AAAAA
